### ISSUE TITLE
Xcode: clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by JustinReinhart** [testfairy/testfairy-unity-plugin#1]
Followed instructions. Failing to compile the XCode project.  Getting an error:
Apple Mach-O Linker Error
Linker command failed with exit code 1

![screenshot 2015-03-17 16 40 49](https://cloud.githubusercontent.com/assets/2589841/6699976/89f793fa-ccc4-11e4-9826-57d2dd6f43f8.png)

![screenshot 2015-03-17 16 46 54](https://cloud.githubusercontent.com/assets/2589841/6700034/4c2c0b2c-ccc5-11e4-9bf9-b4ad4f2f6833.png)

Xcode compiles no problem if I remove the plugin files.

FYI My background is with Unity and C#, not working with Xcode. The errors are unfamiliar to me. Could be something simple but one thing is clear it isn't working out of the box for me by following the instructions.

**Comment by gmegidish** [comment]
`Metal` has been fixed about a year ago. I am truly sorry I forgot to update this github issue. Thanks for the bug report!
