### ISSUE TITLE
Unitypackage doesn't include iOS plugin?

### ISSUE THREAD

**Issue by eugeneloza** [testfairy/testfairy-unity-plugin#13]
Since https://github.com/testfairy/testfairy-unity-plugin/releases/tag/2.30.1 the TestFairySDK-2.3x.x-Unity.unitypackage size dropped from ~13 Mb down to ~450 kb and the iOS plugin seems to be missing from it when opened in Unity Editor. It should have changed, as the changes log (e.g. for 2.32.3) states "Updated iOS SDK to 1.26.1".

![Clipboard 2](https://user-images.githubusercontent.com/10726162/94790280-b937d880-03de-11eb-89e2-4a6f0a212a0b.jpg)
![Clipboard 1](https://user-images.githubusercontent.com/10726162/94790278-b89f4200-03de-11eb-981f-aa18b4f97a19.jpg)

Should I install it manually from the zip archive?

**Comment by gmegidish** [comment]
@eugeneloza Woah! thanks for pointing this out! We're working on a fix. You can also use the manual installation, it's exactly the same framework, just different packaging :). I'll update this issue once a new release is out with the fix. THANKS! 🥇

**Comment by vijaysharm** [comment]
Hi @eugeneloza, I've released version 2.32.4 which should have fixed the issue. Thanks for bringing this issue to our attention!

**Comment by eugeneloza** [comment]
Thank you!!!
