### ISSUE TITLE
Undocumented changes on 2.44.0 release for iOS?

### ISSUE THREAD

**Issue by eugeneloza** [testfairy/testfairy-unity-plugin#15]
Hi all!
I'm having a problem compiling TestFairy 2.44 release in Unity 2020.3.1f1, however, using the Build post-processing script at https://docs.testfairy.com/Platforms/Unity.html#export-adhoc I receive

```
sh: Frameworks/Plugins/iOS/TestFairy.framework/strip-architectures.sh: No such file or directory
** ARCHIVE FAILED **
```

Looking at the package content, indeed, `strip-architectures.sh` was moved from `Plugins/iOS/TestFairy.framework/strip-architectures.s` to `Plugins/iOS/strip-architectures.s`. Is it an accidental error or is that a new change and I have adapt my build script to this new path?

Downgraded to version 2.39.0 and it builds and archives fine now.

**Comment by vijaysharm** [comment]
Hi @eugeneloza thanks for bringing this issue to our attention. The short answer is, yes, you'll have to update your build script to use the new path, and we need to update our docs to reflect the change. However, I believe things may work without the build step/script entirely.

The slightly longer answer is, Xcode causes apps with FAT `.framework` fail compilation and archiving, so we're moving towards Apple's `.xcframework` type, which should eliminate the need for the `strip-architectures.sh` use at all. Unfortunately, Unity only added this support in v2021 for `.xcframework` which means we're in a bit of an awkward transition phase. 

Again, thank you for bringing this to our attention. I will update our docs accordingly. That being said, I'm fairly confident that the build script is no longer required.

**Comment by eugeneloza** [comment]
Thank you for the answer!

I'll update the script then - I'll upgrade our project to Unity 2021 (just noticed that it's out of beta stage), but not within the next week.

**Comment by eugeneloza** [comment]
Hmmm... I've changed the path to `Frameworks/Plugins/iOS/strip-architectures.sh` however, I've noticed that `strip-architectures.sh` isn't copied to the XCodeProject folder at all:
![2021-04-19 03_55_44-Greenshot](https://user-images.githubusercontent.com/10726162/115168323-2a14b880-a0c3-11eb-84b3-ca21fb88d684.png)
though it's definitely contained in the Plugins folder in Unity project:
![2021-04-19 03_56_06-Greenshot](https://user-images.githubusercontent.com/10726162/115168339-34cf4d80-a0c3-11eb-9617-cefdeae4c703.png)
Should I do some additional steps to include it?

**Comment by vijaysharm** [comment]
Hi @eugeneloza I'm terribly sorry about the late response, I'm not sure how your reply escaped my email. Did you manage to resolve your issue. I believe the short answer here, with the version of our library that you're using (i'm deducing the version from the screenshot you provided), you shouldn't need to call `strip-architectures.sh` anymore, and so we no longer package it. And the instructions should be updated. If they arent, i will be doing that myself shortly. 

I believe I misunderstood your first message, we deploy two version of the library in the "Releases" page, one for versions of Unity that include 2021 and beyond and one that should work with all versions. For all intent and purposes, the one that currently works for all versions is deprecated until 2021 becomes the minimum recommended version of Unity. We will continue to support both versions, however, we're trying to nudge anyone that's already moved, or is moving to Unity 2021, to use the 2021 version of our library. And the 2021 version of the library should not need to make use of the `strip-architectures.sh`.

**Comment by eugeneloza** [comment]
Many thanks for your answer! (I also just found the notification e-mail in my inbox, so no problem - that happens to everyone :D)

For now I'm temporarily using 2.39.0 version - it works with our obsolete script. I'll try to follow your advice asap, thank you!

**Comment by eugeneloza** [comment]
Hello!

After the milestone release, I've finally upgraded to Unity 2021.1.7f1 and tried `TestFairySDK-2.50.0-Unity2021.unitypackage`. I've completely deleted the old `Plugins` folder and corresponding build postprocessor script.

However, it wouldn't prepare XCode project with error:

> Plugin 'TestFairy.framework' is used from several locations:
 Assets/Plugins/iOS/TestFairy.xcframework/ios-arm64_arm64e_armv7/TestFairy.framework would be copied to <PluginPath>/TestFairy.framework
 Assets/Plugins/iOS/TestFairy.xcframework/ios-arm64_i386_x86_64-simulator/TestFairy.framework would be copied to <PluginPath>/TestFairy.framework
Please fix plugin settings and try again.

> UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions (string)
UnityEditorInternal.PluginsHelper:CheckFileCollisions (UnityEditor.BuildTarget)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

> Plugins colliding with each other.

> Build completed with a result of 'Failed' in 5 seconds (4960 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

> UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002ca] in <03b7a01d7ff445ec8ed231b348714f65>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <03b7a01d7ff445ec8ed231b348714f65>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Deleting `Assets/Plugins/iOS/TestFairy.xcframework/ios-arm64_i386_x86_64-simulator` fixes the issue (and we don't use the simulator anyway). But then XCode build fails with the following message:

> === BUILD TARGET UnityFramework OF PROJECT Unity-iPhone WITH CONFIGURATION Release ===
Undefined symbols for architecture arm64:
  "_TestFairy_crash", referenced from:
      _TestFairy_crash_m994D214BAB43BBF221E1C7BA6ADA47CD1BA1538D in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_crash_mA6011B69634E3BE65CF2BF43B2CDB489AC2F827C in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_crash_m994D214BAB43BBF221E1C7BA6ADA47CD1BA1538D, _TestFairy_TestFairy_crash_mA6011B69634E3BE65CF2BF43B2CDB489AC2F827C )
  "_TestFairy_takeScreenshotWithCallback", referenced from:
      _TestFairy_TestFairy_takeScreenshotWithCallback_m2750BA1C570D79DC2FC4C0F03317FF1371999038 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_takeScreenshotWithCallback_m481FEDD1C6C40C3B703A931D7BAB88019439D04B, _TestFairy_takeScreenshotWithCallback_m481FEDD1C6C40C3B703A931D7BAB88019439D04B_RuntimeMethod_var , _ReversePInvokeWrapper_TestFairy_takeScreenshotWithCallback_m481FEDD1C6C40C3B703A931D7BAB88019439D04B , _TestFairy_TestFairy_takeScreenshotWithCallback_m2750BA1C570D79DC2FC4C0F03317FF1371999038 )
  "_TestFairy_enableFeedbackForm", referenced from:
      _TestFairy_enableFeedbackForm_mA2513A7E16917C810BD32AC4B4366296C743E682 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_enableFeedbackForm_m7D97892E2A7621950F9A0A2A2924B9A3D956F5F1 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_enableFeedbackForm_m7D97892E2A7621950F9A0A2A2924B9A3D956F5F1, _TestFairy_enableFeedbackForm_mA2513A7E16917C810BD32AC4B4366296C743E682 )
  "_TestFairy_disableMetric", referenced from:
      _TestFairy_disableMetric_m04ABDBAEA073EAC691708D725B4DA1FFE97F7E9C in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_disableMetric_m7EB7C0D1A3B1DDCDFF8FD5E80F2A56C186BCB73E in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_disableMetric_m04ABDBAEA073EAC691708D725B4DA1FFE97F7E9C, _TestFairy_TestFairy_disableMetric_m7EB7C0D1A3B1DDCDFF8FD5E80F2A56C186BCB73E )
  "_TestFairy_enableMetric", referenced from:
      _TestFairy_enableMetric_m5E9D8D770411FC48A9614F66C25C19ECADC2A8DE in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_enableMetric_m6EBC45535D0DC52B9D17930DFF3132CDF4BB62E1 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_enableMetric_m6EBC45535D0DC52B9D17930DFF3132CDF4BB62E1, _TestFairy_enableMetric_m5E9D8D770411FC48A9614F66C25C19ECADC2A8DE )
  "_TestFairy_disableCrashHandler", referenced from:
      _TestFairy_disableCrashHandler_mE18102DFDAC370D5E3929305B6AA17DDF6CD5968 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_disableCrashHandler_mDACC3EC010E02C17096F20AEEDDAB87F69CA5CCD in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_disableCrashHandler_mE18102DFDAC370D5E3929305B6AA17DDF6CD5968, _TestFairy_TestFairy_disableCrashHandler_mDACC3EC010E02C17096F20AEEDDAB87F69CA5CCD )
  "_TestFairy_enableCrashHandler", referenced from:
      _TestFairy_enableCrashHandler_m3838502AA3DFC86C3290D7B65535C75417CE2186 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_enableCrashHandler_mCF1AC19BAC1D38D9A5DBD06EFB2294B9AECFACCA in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_enableCrashHandler_m3838502AA3DFC86C3290D7B65535C75417CE2186, _TestFairy_TestFairy_enableCrashHandler_mCF1AC19BAC1D38D9A5DBD06EFB2294B9AECFACCA )
  "_TestFairy_version", referenced from:
      _TestFairy_version_m659D9D2A08B771F25B31B30BB3D5491742E40501 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_version_m12CC43A1380E1CAE3B15C42AAB690187446FC479 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_version_m659D9D2A08B771F25B31B30BB3D5491742E40501, _TestFairy_TestFairy_version_m12CC43A1380E1CAE3B15C42AAB690187446FC479 )
  "_TestFairy_disableVideo", referenced from:
      _TestFairy_disableVideo_m690433B99B946773F471BAA87D9DC5CDA0DBACCB in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_disableVideo_m02BBB4D1ECD89A758B90089008EB38ADDFFEA152 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_disableVideo_m02BBB4D1ECD89A758B90089008EB38ADDFFEA152, _TestFairy_disableVideo_m690433B99B946773F471BAA87D9DC5CDA0DBACCB )
  "_TestFairy_sendUserFeedbackWithImage", referenced from:
      _TestFairy_TestFairy_sendUserFeedbackWithImage_mD328B2110EE04DAD6C913F06066A309211C07CBB in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_sendUserFeedbackWithImage_mD328B2110EE04DAD6C913F06066A309211C07CBB)
  "_TestFairy_sendUserFeedback", referenced from:
      _TestFairy_sendUserFeedback_m75B5DC2D08B4699D152E88583672C9C4C4C62CD7 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_sendUserFeedback_m8BAB7E13D16A9AD0D5265DBE22B4762F9607038F in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_sendUserFeedback_m8BAB7E13D16A9AD0D5265DBE22B4762F9607038F, _TestFairy_TestFairy_sendUserFeedbackWithImage_mD328B2110EE04DAD6C913F06066A309211C07CBB , _TestFairy_sendUserFeedback_m75B5DC2D08B4699D152E88583672C9C4C4C62CD7 , _TestFairy_sendUserFeedback_m26A5104C9F718F0EB10EA1552095BFBF17B66EFF )
  "_TestFairy_setServerEndpoint", referenced from:
      _TestFairy_setServerEndpoint_m2F1AF5E70802958F1CE1DD4DEFF176B9D0EE0C15 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_setServerEndpoint_m7E2C8DBD59525D7C526BCE692D49E8AB38D4216B in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_setServerEndpoint_m7E2C8DBD59525D7C526BCE692D49E8AB38D4216B, _TestFairy_setServerEndpoint_m2F1AF5E70802958F1CE1DD4DEFF176B9D0EE0C15 )
  "_TestFairy_takeScreenshot", referenced from:
      _TestFairy_takeScreenshot_mC9A7A5B3629C056713889F34165887D982CD9F98 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_takeScreenshot_m8863A01E888E20FA053008F093A951B80FAC1885 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_takeScreenshotWithCallback_m481FEDD1C6C40C3B703A931D7BAB88019439D04B, _TestFairy_takeScreenshotWithCallback_m481FEDD1C6C40C3B703A931D7BAB88019439D04B_RuntimeMethod_var , _ReversePInvokeWrapper_TestFairy_takeScreenshotWithCallback_m481FEDD1C6C40C3B703A931D7BAB88019439D04B , _TestFairy_TestFairy_takeScreenshotWithCallback_m2750BA1C570D79DC2FC4C0F03317FF1371999038 , _TestFairy_TestFairy_takeScreenshot_m8863A01E888E20FA053008F093A951B80FAC1885 , _TestFairy_takeScreenshot_mC9A7A5B3629C056713889F34165887D982CD9F98 , _TestFairy_takeScreenshot_mA812C23C9112524E205C852704FA84C86D12C62A )
  "_TestFairy_stop", referenced from:
      _TestFairy_stop_m10FEE93AD0A94057CD368329A9F9309369B576A9 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_stop_m9C11565D78758E7D2095D27FECC957A93F54A248 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_stop_m9C11565D78758E7D2095D27FECC957A93F54A248, _TestFairy_stop_m10FEE93AD0A94057CD368329A9F9309369B576A9 )
  "_TestFairy_resume", referenced from:
      _TestFairy_resume_mDB73DD67D0BC06CFEBBE528B2D2FEEBE091CDF23 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_resume_mA627BB4A3ABC423D166F4661CBE65E31DE86D73D in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_resume_mDB73DD67D0BC06CFEBBE528B2D2FEEBE091CDF23, _TestFairy_TestFairy_resume_mA627BB4A3ABC423D166F4661CBE65E31DE86D73D )
  "_TestFairy_pause", referenced from:
      _TestFairy_pause_mEC5864B51905CFAECA9904440A9F15F0530732AA in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_pause_m05D12B8DE8621219D3556AB9C97B3BA8D6E68AF7 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_pause_mEC5864B51905CFAECA9904440A9F15F0530732AA, _TestFairy_TestFairy_pause_m05D12B8DE8621219D3556AB9C97B3BA8D6E68AF7 )
  "_TestFairy_disableAutoUpdate", referenced from:
      _TestFairy_disableAutoUpdate_m09154D3179A45662EC21A26C10CC8854E758B243 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_disableAutoUpdate_mD84878C5BF7C13D698666DA92AE5AC406295DAB2 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_disableAutoUpdate_mD84878C5BF7C13D698666DA92AE5AC406295DAB2, _TestFairy_disableAutoUpdate_m09154D3179A45662EC21A26C10CC8854E758B243 )
  "_TestFairy_checkpoint", referenced from:
      _TestFairy_checkpoint_mC84981F50CC108CD2BE047E04EF8EAF2FB9C6404 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_checkpoint_mC5FD6AD475D5577AF15C763F977AEC3A067C8FA7 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_checkpoint_mC84981F50CC108CD2BE047E04EF8EAF2FB9C6404, _TestFairy_TestFairy_checkpoint_mC5FD6AD475D5577AF15C763F977AEC3A067C8FA7 )
  "_TestFairy_setUserId", referenced from:
      _TestFairy_setUserId_mCE532BD2C3D4E6DCAE8C249D74A9D0969CEAC502 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_setUserId_m965265CB4A98AEC7E7FD3E0CD48D01E447860845 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_setUserId_m965265CB4A98AEC7E7FD3E0CD48D01E447860845, _TestFairy_setUserId_mCE532BD2C3D4E6DCAE8C249D74A9D0969CEAC502 )
  "_TestFairy_pushFeedbackController", referenced from:
      _TestFairy_pushFeedbackController_m60608FA1797C62A4A875187702888543A78C4795 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_pushFeedbackController_mE608A7F8C07AE7AA1820F253A5F86C2925BAFA4A in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_pushFeedbackController_mE608A7F8C07AE7AA1820F253A5F86C2925BAFA4A, _TestFairy_pushFeedbackController_m60608FA1797C62A4A875187702888543A78C4795 )
  "_TestFairy_enableVideo", referenced from:
      _TestFairy_TestFairy_enableVideo_mA3EEB00DDCEABBE75039EDC91BE0BB9D54E07BEC in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_enableVideo_m7558FA5D37535436054128A2B31CA908306A744C, _TestFairy_TestFairy_enableVideo_mA3EEB00DDCEABBE75039EDC91BE0BB9D54E07BEC )
  "_TestFairy_setScreenName", referenced from:
      _TestFairy_setScreenName_mE5F1A43AE6DC6764C01B6E8F6A6DAF13FB55AA8E in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_setScreenName_m5A33D464181F2AC2942304D0D13390B602944984 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_setScreenName_m5A33D464181F2AC2942304D0D13390B602944984, _TestFairy_setScreenName_mE5F1A43AE6DC6764C01B6E8F6A6DAF13FB55AA8E )
  "_TestFairy_sessionUrl", referenced from:
      _TestFairy_sessionUrl_mC844FC60E7B160CA85E7C72645DE7FB738391BCA in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_sessionUrl_mCB095122274C431DFE0B1D344C4F5E2503F758D7 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_sessionUrl_mC844FC60E7B160CA85E7C72645DE7FB738391BCA, _TestFairy_TestFairy_sessionUrl_mCB095122274C431DFE0B1D344C4F5E2503F758D7 )
  "_TestFairy_installFeedbackHandler", referenced from:
      _TestFairy_TestFairy_installFeedbackHandler_m0A5755A5E28AC6E7742273DF46A7CCA30E12F400 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_installFeedbackHandler_m0A5755A5E28AC6E7742273DF46A7CCA30E12F400, _TestFairy_installFeedbackHandler_mAA54D8D23419AEF9C8C3F96D9F418DBA426CB74A )
  "_TestFairy_showFeedbackForm", referenced from:
      _TestFairy_showFeedbackForm_mA638F8AC3C5D9DC81A975CBBF4FCFA83F27487A3 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_showFeedbackForm_m2983AFA65AD0E80EBA13B520E884CC44DD0429A3 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_showFeedbackForm_mA638F8AC3C5D9DC81A975CBBF4FCFA83F27487A3, _TestFairy_TestFairy_showFeedbackForm_m2983AFA65AD0E80EBA13B520E884CC44DD0429A3 )
  "_TestFairy_disableFeedbackForm", referenced from:
      _TestFairy_disableFeedbackForm_m9EE88043B9CEE6AB7E5DE03A1D1E0AADA5792668 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_disableFeedbackForm_m924EA2538D1160748D6802F6FECC40F5D6B46EE9 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_disableFeedbackForm_m9EE88043B9CEE6AB7E5DE03A1D1E0AADA5792668, _TestFairy_TestFairy_disableFeedbackForm_m924EA2538D1160748D6802F6FECC40F5D6B46EE9 )
  "_TestFairy_hideWebViewElements", referenced from:
      _TestFairy_hideWebViewElements_m63F963856BE0EF64A48D7DF409503656ADCA7BBD in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_hideWebViewElements_m5616996BCD816A765C485A2B238F783671F40D70 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_hideWebViewElements_m63F963856BE0EF64A48D7DF409503656ADCA7BBD, _TestFairy_TestFairy_hideWebViewElements_m5616996BCD816A765C485A2B238F783671F40D70 )
  "_TestFairy_logException", referenced from:
      _TestFairy_TestFairy_logException_m8436CF608287DDD04F5E946BFD4127BD6C65EE6E in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_TestFairy_logException_m8436CF608287DDD04F5E946BFD4127BD6C65EE6E, _TestFairy_logException_mAC97384B5D7605F6F5322FA73C1EE88B43E84782 )
  "_TestFairy_begin", referenced from:
      _TestFairy_begin_m8C1D9D2D0D5B356E80955812FC0598BB22AF62A1 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_begin_m0D612D5EF468DEAEFA2CD4B579F8ACABFE6DA78E in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_begin_m8C1D9D2D0D5B356E80955812FC0598BB22AF62A1, _TestFairy_TestFairy_begin_m0D612D5EF468DEAEFA2CD4B579F8ACABFE6DA78E )
  "_TestFairy_setAttribute", referenced from:
      _TestFairy_TestFairy_setAttribute_m58C369D6A469842BF9119112B097FC1DC68B76F7 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_setAttribute_mD367805AB6A003B0F6FBB4D651FC7491E457867C, _TestFairy_TestFairy_setAttribute_m58C369D6A469842BF9119112B097FC1DC68B76F7 )
  "_TestFairy_setCorrelationId", referenced from:
      _TestFairy_setCorrelationId_mD78AED7F0A3167E5A88C3EDBE3693B15DDAB6F11 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_setCorrelationId_m112E95CB65F33A8F7235734E261ADD51E86445EE in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_setCorrelationId_mD78AED7F0A3167E5A88C3EDBE3693B15DDAB6F11, _TestFairy_TestFairy_setCorrelationId_m112E95CB65F33A8F7235734E261ADD51E86445EE )
  "_TestFairy_identify", referenced from:
      _TestFairy_TestFairy_identify_m094FAA52C0290EB004EC3421B0A5594245CCBA7D in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_identify_m5E0EAF2D1372D964B82270F66253D177CF73B74F, _TestFairy_TestFairy_identify_m094FAA52C0290EB004EC3421B0A5594245CCBA7D )
  "_TestFairy_log", referenced from:
      _TestFairy_log_mE2A45A25ABA740BD00980624CF7CA51BE0081FD3 in Assembly-CSharp-firstpass.o
      _TestFairy_TestFairy_log_m69A3F2CDFD8F2DE1892126581503E9F678035327 in Assembly-CSharp-firstpass.o
     (maybe you meant: _TestFairy_logMsgRecvThreaded_m89BFC64DFB251374439107772ED5816FA1AA8A5E_RuntimeMethod_var, _TestFairy_log_mE2A45A25ABA740BD00980624CF7CA51BE0081FD3 , _TestFairy_TestFairy_log_m69A3F2CDFD8F2DE1892126581503E9F678035327 , _TestFairy_TestFairy_logException_m8436CF608287DDD04F5E946BFD4127BD6C65EE6E , _TestFairy_logMsgRecvThreaded_m89BFC64DFB251374439107772ED5816FA1AA8A5E , _TestFairy_logException_mAC97384B5D7605F6F5322FA73C1EE88B43E84782 )
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** ARCHIVE FAILED **

Note that before that there is a message:

>Manually calling TestFairy strip-architectures.sh, if needed
TestFairy.framework for iOS not found, aborting strip-architectures.sh call
Using Xcode: /Applications/Xcode.app/Contents/Developer

Though (I've just double-checked) we never seem to call this script explicitly anywhere in our code.

The `TestFairy.framework` seems to be created correctly inside the XCode project folder:

![2021-05-24 17_33_49-Greenshot](https://user-images.githubusercontent.com/10726162/119363248-443f4900-bcb6-11eb-8eb9-3763d56635dd.png)

But still either lacks some additional script to run, or doesn't copy some essential library

Maybe some additional steps are needed?

**Comment by vijaysharm** [comment]
Hey @eugeneloza! Thanks for the follow up! I'll look into this, and get back to you. 

Could you let me know what version of Xcode you have installed as well?

**Comment by eugeneloza** [comment]
XCode version 12.1 (12A7403) on Catalina.

**Comment by vijaysharm** [comment]
I'm sorry for the embarrassingly late reply, but could you try the latest version https://github.com/testfairy/testfairy-unity-plugin/releases/tag/2.60.1 of this package. I believe it should be fixed in that version.
